//! Reading a work into segments that carry their own permanent names.
//!
//! spec.md §4.1: **text files on disk are the truth, the database is a
//! rebuildable cache.** So an import writes files, and the files have to be
//! greppable, diffable and readable without the app.
//!
//! # The one thing the on-disk form may not do
//!
//! It may not imply a segment's id from its **position in the file**. That is
//! T1 — the defect the whole corpus is being rebuilt to escape — reintroduced
//! at the last possible moment: insert a line into a segments file whose ids
//! are line numbers and every anchor below it silently names different words.
//!
//! So each record carries its id as a field:
//!
//! ```jsonl
//! {"id":"girsa:mishnah-berurah/1:1#30","kind":"text","text":"…"}
//! {"id":"girsa:mishnah-berurah/1:2#31","kind":"text","text":"…"}
//! ```
//!
//! One line per segment, so `grep` still works and a diff of a corrected sefer
//! is readable; but the name is *in* the line, so sorting, re-ordering,
//! inserting and deleting are all safe, and a split writes `#30.1` and `#30.2`
//! wherever it likes.
//!
//! # The second file, and why it is not optional
//!
//! `redirects.jsonl` sits beside `segments.jsonl` and says where the names that
//! are no longer live went:
//!
//! ```jsonl
//! {"from":"girsa:shulchan-arukh/orach-chayim/1:1#32","to":["…#32.1","…#32.2"],"why":"cut"}
//! {"from":"girsa:shulchan-arukh/orach-chayim/1:5#5","to":["…/1:4#4"],"why":"resegmented"}
//! {"from":"girsa:shulchan-arukh/orach-chayim/1:9#9","to":[],"why":"gone"}
//! ```
//!
//! Without it the format has nowhere to keep the one thing spec.md §3 says the
//! design rests on. `SegmentStore` has held a redirect table since W6 and lost
//! every row of it the moment the work was written to disk, so the promise in
//! its doc comment — *"a Ksav document written last year still opens"* — held
//! exactly as long as nobody re-ran the importer. See [`continuity`].

pub mod continuity;
pub mod mine;
pub mod otzaria;
pub mod sefaria;

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::oversized;
use crate::segment::SegmentId;
use crate::work::{Source, Work};

/// What a segment is, as far as the reader is concerned.
///
/// The distinction is load-bearing twice over: spec.md §2.1 counts Mishnah
/// Berurah as *"18,120 lines with 701 headings"*, which is only checkable if
/// the two are told apart; and a search hit inside a heading is a different
/// kind of result from one inside the text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SegmentKind {
    Text,
    /// A structural heading — Otzaria's `<h1>/<h2>/<h3>`, or a Sefaria schema
    /// node that names a section rather than holding one.
    Heading,
    /// A page of a scan you brought (spec.md §6.3). It is addressable and
    /// citable now and it has **no words** until it is OCR'd — which is a
    /// different thing from a segment that is empty, and search has to be able
    /// to tell them apart so that a PDF is *"not searchable yet"* rather than
    /// silently absent (§9.7).
    Page,
    /// A footnote, lifted out of the sentence that carried it (W29).
    ///
    /// Its own segment on purpose. A note spliced into the words around it
    /// corrupts them — the sentence reads as though the author wrote the note
    /// into it — and a note that is its own segment is searchable, citable and
    /// correctable like any other line.
    Note,
    /// One item of a list.
    Item,
    /// One row of a table, its cells kept apart.
    Row,
    /// A block quote — text this sefer is quoting rather than saying.
    Quote,
}

crate::spelled!(SegmentKind {
    Text => "text",
    Heading => "heading",
    Page => "page",
    Note => "note",
    Item => "item",
    Row => "row",
    Quote => "quote",
});

impl SegmentKind {
    /// Every kind, in the order they are written above.
    #[must_use]
    pub fn all() -> [Self; 7] {
        let mut out = [Self::Text; 7];
        let mut at = 0;
        while at < Self::SPELLINGS.len() {
            out[at] = Self::SPELLINGS[at].0;
            at += 1;
        }
        out
    }

    /// Whether this segment is the sefer's own running text.
    ///
    /// False for a heading, which names a section rather than holding one, and
    /// for a page with no words in it yet. **True for a note, an item, a row
    /// and a quote**: those are words somebody wrote and are read, searched and
    /// corrected like any other line — they are only drawn differently.
    #[must_use]
    pub const fn has_words(self) -> bool {
        !matches!(self, Self::Page)
    }

    /// Read back what [`SegmentKind::as_str`] wrote.
    ///
    /// The search index stores the kind as this word — a result row says which
    /// it is, and W14's facets count by it. `named` is the one generated by
    /// [`crate::spelled`]; this is the name the rest of the tree already calls
    /// it by.
    #[must_use]
    pub fn parse(word: &str) -> Option<Self> {
        Self::named(word)
    }
}

/// A segment as it goes to disk: its permanent name, and its words.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Segment {
    pub id: SegmentId,
    pub kind: SegmentKind,
    pub text: String,
    /// Where commentaries attach, mined out of the text at ingest (W34, W33-A).
    ///
    /// Sefaria writes them inline as empty `<i data-commentator="…"></i>` elements —
    /// 43,883 of them in Shulchan Arukh Orach Chayim alone, 61% of that file's bytes
    /// — and they were being **indexed as words**, so a phrase search for a line
    /// printed in front of the reader missed it. They are `spec.md` §8.4's span
    /// anchoring, already computed upstream and sitting in the corpus unused; this is
    /// where they become that rather than noise.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub anchors: Vec<crate::anchors::Anchor>,
}

/// Why a permanent id stopped being live.
///
/// Named rather than inferred. `places_of` has to tell a cut apart from a
/// re-segmentation to reassemble what a previous run judged, and a reader
/// deserves to know whether the place it is looking for was divided or is
/// simply not in this edition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Why {
    /// Too long to name a place, so this importer cut it into places (B12).
    /// `to` is its children and their texts concatenate back to its own.
    Cut,
    /// Upstream re-drew the boundaries and the words are in `to` now.
    Resegmented,
    /// Upstream does not have this place at all any more. `to` is empty, and
    /// that is an answer: an anchor on it resolves to nothing *and can say
    /// why*, which is not the same as an id nobody ever minted.
    Gone,
}

crate::spelled!(Why {
    Cut => "cut",
    Resegmented => "resegmented",
    Gone => "gone",
});

/// Where a name that is no longer live points now.
///
/// One mechanism for three events, because from an anchor's point of view they
/// are the same one: *what I named is over there now*.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Redirect {
    pub from: SegmentId,
    pub to: Vec<SegmentId>,
    pub why: Why,
}

/// What the last import left on disk for this work, ready to be kept faith with.
///
/// [`Previous::none`] is a first import and costs nothing: the ordinals come out
/// of enumeration position exactly as they always did, because there is no
/// earlier promise to keep.
#[derive(Debug, Clone, Default)]
pub struct Previous {
    places: Vec<continuity::Place>,
    redirects: Vec<Redirect>,
}

impl Previous {
    /// Nothing on the shelf yet.
    #[must_use]
    pub fn none() -> Self {
        Self::default()
    }

    /// Read what is on the shelf for `slug`, or nothing if it is not there.
    ///
    /// A work that will not parse reads as nothing rather than failing the
    /// import: the alternative is refusing to re-import a shelf that a half-
    /// written file has damaged, and the names in a damaged file are not names
    /// worth keeping anyway. It is counted by the caller either way.
    #[must_use]
    pub fn on_the_shelf(root: &Path, slug: &str) -> Self {
        match read_back(root, slug) {
            Ok(previous) => Self {
                places: continuity::places_of(&previous.segments, &previous.redirects),
                redirects: previous.redirects,
            },
            Err(_) => Self::none(),
        }
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.places.is_empty()
    }
}

/// A segment before it has been given a name.
///
/// What the two source parsers produce. Ordinals are assigned in exactly one
/// place — [`ImportedWork::assemble`] — so that "assigned once, in reading
/// order, never recomputed" is a property of the code and not of a convention.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawSegment {
    pub path: Vec<String>,
    pub kind: SegmentKind,
    pub text: String,
}

/// One work, read.
#[derive(Debug, Clone)]
pub struct ImportedWork {
    pub work: Work,
    pub segments: Vec<Segment>,
    /// What was too long to be a place, and what was done about it (B12).
    ///
    /// Counted on the way through `assemble`, so the number in the import's report
    /// is the number the importer acted on rather than a second measurement.
    pub oversized: oversized::Tally,
    /// Every name that is no longer live, and where it went.
    ///
    /// Written to `redirects.jsonl` and read back by the next import and by the
    /// reading pane. Never empty for a work with a cut segment in it, which is
    /// what keeps this file exercised by real data rather than being a slot
    /// nothing ever fills.
    pub redirects: Vec<Redirect>,
    /// How many of this work's places kept the name they had (spec.md §3).
    ///
    /// All zero for a first import: there was no name to keep.
    pub continuity: continuity::Continuity,
}

/// What an import found, for asserting against spec.md §2.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Counts {
    pub works: usize,
    pub segments: usize,
    pub headings: usize,
    /// Works that produced no segments at all. Loud rather than silent: an
    /// empty sefer on the shelf is a defect, not a small book.
    pub empty_works: usize,
    /// Segments whose id would not survive being written down and read back.
    /// Must be zero — see [`SegmentId::is_well_formed`].
    pub malformed_ids: usize,
}

impl ImportedWork {
    /// Give every segment its permanent name, in reading order, once.
    ///
    /// # A segment too long to be a place is cut into places
    ///
    /// 5,733 of the corpus's 5,000,545 segments are over 10,000 characters and the
    /// largest is 1,275,307 — a permanent id naming 1.2 MB of text, which names a
    /// volume and not a place (see [`crate::oversized`]). A citation to it is
    /// unusable as a mareh makom, a highlight cannot help, and a search result over
    /// it is *"it is somewhere in here."*
    ///
    /// So this is where they are cut, because this is the one place ordinals are
    /// handed out. **Nothing anchored to the parent breaks**: `#32` split gives
    /// `#32.1 #32.2 #32.3`, and [`Ordinal::covers`](crate::segment::Ordinal::covers)
    /// says `#32` covers all three — which is exactly the property spec.md §3
    /// minted the ordinal scheme for. A Ksav document, a link, a correction or a
    /// mark on `#32` still names the same words, as a group rather than as one
    /// record.
    ///
    /// The tally of what was cut goes on `oversized`, so the import reports it the
    /// way it reports everything else.
    ///
    /// A cut is also written down. `#32` covering `#32.1 #32.2 #32.3` is what
    /// keeps an anchor on the parent working *inside one run*, and it is not
    /// enough on its own: the next import has to be able to see that those three
    /// records were one se'if, or it will compare a whole se'if against a third
    /// of one and match neither. So the cut goes to disk as a [`Why::Cut`] row.
    #[must_use]
    pub fn assemble(work: Work, raw: Vec<RawSegment>) -> Self {
        Self::assemble_after(work, raw, &Previous::none())
    }

    /// The same, keeping every name the previous import already handed out.
    ///
    /// # Why this is not a nicety
    ///
    /// spec.md §3 is about T1: an id derived from position means inserting one
    /// line silently re-points every anchor below it. `assemble` derives the id
    /// from position. It did so once per work and called that *"once in the life
    /// of a work"*, which was a claim about the world rather than about the
    /// code — `girsa-import` runs over the whole catalogue on every invocation
    /// and [`write`] is an unconditional overwrite. Sefaria adding one se'if to
    /// siman 1 of Orach Chayim renumbered 4,170 segments by one, which is T1
    /// verbatim at import granularity, and `--metadata-only` exists precisely
    /// because somebody expected the importer to be re-run.
    ///
    /// So the names come from [`continuity::align`] when there is a previous run
    /// to keep faith with, and from enumeration position only when there is not.
    #[must_use]
    pub fn assemble_after(work: Work, raw: Vec<RawSegment>, previous: &Previous) -> Self {
        // Mined first, and once. 61% of a heavily-commented sefer's bytes are
        // markup, so both the length judgement and the text the alignment
        // matches on have to be the mined text — the previous run's file holds
        // the mined text and nothing else.
        let mined: Vec<crate::anchors::Mined> =
            raw.iter().map(|r| crate::anchors::mine(&r.text)).collect();
        let fresh: Vec<continuity::Fresh<'_>> = raw
            .iter()
            .zip(&mined)
            .map(|(r, m)| continuity::Fresh {
                path: &r.path,
                kind: r.kind,
                text: &m.text,
            })
            .collect();

        let Named {
            ordinals,
            carried,
            went,
            mut tally,
        } = name_them(&fresh, previous);
        if !previous.is_empty() {
            tally.over(&work.slug);
        }

        let mut redirects: Vec<Redirect> = Vec::new();
        let mut oversized = oversized::Tally::default();
        let mut segments = Vec::new();
        // Where each place's live ids ended up, so a redirect away from an old
        // place can point at records that exist rather than at a name.
        let mut live_of: Vec<Vec<SegmentId>> = Vec::with_capacity(fresh.len());
        for ((raw, mined), ordinal) in raw.into_iter().zip(mined).zip(ordinals) {
            let id = SegmentId::new(work.slug.clone(), raw.path, ordinal);
            oversized.saw(&id.to_string(), mined.text.chars().count(), &work.slug);
            let pieces = oversized::pieces(&mined.text, oversized::TARGET);
            if pieces.len() == 1 {
                live_of.push(vec![id.clone()]);
                segments.push(Segment {
                    id,
                    kind: raw.kind,
                    text: mined.text,
                    anchors: mined.anchors,
                });
                continue;
            }
            oversized.cut(pieces.len());
            // The children, in reading order. The parent id is not written to disk:
            // it is not a segment any more, and `covers` is what keeps it resolvable
            // rather than a record that would be a second copy of the same words.
            // Each child keeps the anchors that fall inside it, with their offsets
            // rebased — an anchor is a position in a text, and after a split it is a
            // position in a different, shorter text.
            let children = id.split(pieces.len());
            live_of.push(children.clone());
            redirects.push(Redirect {
                from: id,
                to: children.clone(),
                why: Why::Cut,
            });
            let mut from = 0usize;
            for (child, piece) in children.into_iter().zip(pieces) {
                let upto = from + piece.chars().count();
                let anchors = mined
                    .anchors
                    .iter()
                    .filter(|a| a.at >= from && a.at < upto)
                    .map(|a| crate::anchors::Anchor {
                        at: a.at - from,
                        ..a.clone()
                    })
                    .collect();
                segments.push(Segment {
                    id: child,
                    kind: raw.kind,
                    text: piece.to_string(),
                    anchors,
                });
                from = upto;
            }
        }

        // The rows that could only be written once the new records existed:
        // where a place upstream no longer has sent its anchors. `went` names
        // the places by their position in this run; the ids they turned out to
        // be on disk are only knowable after the cutter has had its say, so a
        // re-segmented se'if that was then cut into three redirects to all
        // three rather than to a name with no record behind it.
        for (from, at) in went {
            let to: Vec<SegmentId> = at.iter().flat_map(|i| live_of[*i].clone()).collect();
            let why = if to.is_empty() {
                Why::Gone
            } else {
                Why::Resegmented
            };
            redirects.push(Redirect { from, to, why });
        }
        // Rows the previous run wrote, kept last so that anything this run
        // decided about the same name wins. A carried row whose name is live
        // again — upstream restored a se'if it had dropped — is not carried:
        // the name resolves to itself now and a redirect over the top of it
        // would send a reader somewhere else.
        let live: std::collections::BTreeSet<&SegmentId> = segments.iter().map(|s| &s.id).collect();
        redirects.extend(carried.into_iter().filter(|row| !live.contains(&row.from)));
        redirects.sort_by(|a, b| a.from.cmp(&b.from));
        redirects.dedup_by(|a, b| a.from == b.from);

        Self {
            work,
            segments,
            oversized,
            redirects,
            continuity: tally,
        }
    }

    #[must_use]
    pub fn counts(&self) -> Counts {
        Counts {
            works: 1,
            segments: self.segments.len(),
            headings: self
                .segments
                .iter()
                .filter(|s| s.kind == SegmentKind::Heading)
                .count(),
            empty_works: usize::from(self.segments.is_empty()),
            malformed_ids: self
                .segments
                .iter()
                .filter(|s| !s.id.is_well_formed())
                .count(),
        }
    }
}

/// What [`name_them`] decided, before anything has been cut or written.
struct Named {
    /// One per place in the run, in reading order.
    ordinals: Vec<crate::segment::Ordinal>,
    /// Rows the previous run wrote, to be kept unless this one overrules them.
    carried: Vec<Redirect>,
    /// A previous place with no continuation, and the places in *this* run its
    /// words turned up in — by position, because the ids they will be on disk
    /// as are not decided until the oversized cutter has run.
    went: Vec<(SegmentId, Vec<usize>)>,
    tally: continuity::Continuity,
}

/// Hand out this run's permanent names.
///
/// One name per place, and the only two ways a place can get one:
///
/// - it is the continuation of a place the previous run named, and keeps that
///   name — whatever its address is now;
/// - it is new, and gets a name minted **between its neighbours**, which the
///   dotted ordinal can always express and which moves nothing.
///
/// There is no third way, and in particular no name is ever handed out twice.
/// `taken` is seeded with every ordinal the previous run used *including the
/// ones nothing continued*: a se'if upstream dropped may still be named by a
/// link, a correction or a Ksav document on somebody else's disk, and giving
/// its name to different words is the exact failure spec.md §3 exists to
/// prevent — worse than the anchor resolving to nothing, because it is silent.
fn name_them(fresh: &[continuity::Fresh], previous: &Previous) -> Named {
    // A first import. The names come out of reading order, once, which is what
    // §3 asks for and what this has always done.
    if previous.is_empty() {
        return Named {
            ordinals: (1..=fresh.len())
                .map(|n| {
                    #[allow(clippy::cast_possible_truncation)]
                    crate::segment::Ordinal::root(n as u32)
                })
                .collect(),
            carried: previous.redirects.clone(),
            went: Vec::new(),
            tally: continuity::Continuity::default(),
        };
    }

    let aligned = continuity::align(&previous.places, fresh);
    let mut taken: std::collections::BTreeSet<crate::segment::Ordinal> = previous
        .places
        .iter()
        .map(|p| p.ordinal.clone())
        .chain(previous.redirects.iter().map(|r| r.from.ordinal().clone()))
        .collect();

    let mut tally = continuity::Continuity::default();
    let mut ordinals: Vec<Option<crate::segment::Ordinal>> = vec![None; fresh.len()];
    for (at, was) in aligned.for_fresh.iter().enumerate() {
        if let Some(was) = was {
            ordinals[at] = Some(previous.places[*was].ordinal.clone());
            tally.kept += 1;
        }
    }

    // Runs of consecutive new places, each between the two kept names that
    // bracket it. Done a run at a time so five inserted se'ifim read as
    // `#5.1 … #5.5` rather than nesting five deep.
    let mut at = 0usize;
    while at < ordinals.len() {
        if ordinals[at].is_some() {
            at += 1;
            continue;
        }
        let from = at;
        while at < ordinals.len() && ordinals[at].is_none() {
            at += 1;
        }
        let low = from.checked_sub(1).and_then(|i| ordinals[i].clone());
        let high = ordinals.get(at).cloned().flatten();
        let minted = continuity::mint_between(low.as_ref(), high.as_ref(), at - from, &mut taken);
        tally.minted += minted.len();
        for (slot, name) in ordinals[from..at].iter_mut().zip(minted) {
            *slot = Some(name);
        }
    }

    // Where the places nothing continued should send their anchors. Searched
    // only inside the stretch of this run that the alignment already narrowed
    // them to — a text matching somewhere else entirely in the sefer is a
    // coincidence, and following it would be exactly the silent wrongness this
    // is all arranged against.
    let kept: Vec<(usize, usize)> = aligned
        .for_fresh
        .iter()
        .enumerate()
        .filter_map(|(at, was)| was.map(|w| (w, at)))
        .collect();
    let mut went = Vec::new();
    for orphan in &aligned.orphaned {
        let old = &previous.places[*orphan];
        let within = gap_around(*orphan, &kept, fresh.len());
        let at = continuity::went_to(old, fresh, within);
        if at.is_empty() {
            tally.gone += 1;
        } else {
            tally.resegmented += 1;
        }
        // Every id the place was on disk as, not only its own name: a se'if
        // that was cut into three has three names in circulation and all three
        // have to be told where the words went.
        for id in &old.ids {
            went.push((id.clone(), at.clone()));
        }
    }

    // One name per place, and the count has to come out right. `flatten` here
    // would drop a segment on the floor and hand back a shorter sefer, which is
    // the shape of failure `read_back` refuses a malformed line for.
    let mut out = Vec::with_capacity(ordinals.len());
    for slot in ordinals {
        match slot {
            Some(name) => out.push(name),
            // Unreachable — the loop above fills every run. Total anyway.
            None => out.extend(continuity::mint_between(out.last(), None, 1, &mut taken)),
        }
    }
    Named {
        ordinals: out,
        carried: previous.redirects.clone(),
        went,
        tally,
    }
}

/// How far a re-segmentation is allowed to have moved a place's words.
///
/// A gap wider than this is not upstream redrawing a boundary; it is a work
/// that was replaced, and searching it would be O(orphans × segments) text
/// comparisons — 328 million of them on a Mishnah Berurah whose alignment found
/// nothing. Past the cap the answer is [`Why::Gone`], which is the honest one:
/// nothing here says where those words went.
const A_RESEGMENTATION_IS_LOCAL: usize = 64;

/// The stretch of this run that a previous place at `orphan` could have gone
/// into: from the nearest kept name before it to the nearest kept one after,
/// **including both**.
///
/// Including them is the merge case and it is the common one. Upstream folding
/// se'if 3 into se'if 2 leaves se'if 2 matched — same address, same opening —
/// and se'if 3's words are inside it. A range that stopped short of the
/// brackets would look at the one place the words are not and report `gone`
/// over an anchor that still resolves perfectly.
///
/// `kept` is `(previous position, position in this run)` for every place that
/// kept its name, ascending in both — which is what [`continuity::align`]
/// guarantees, and is why this can be a binary search rather than a scan.
fn gap_around(orphan: usize, kept: &[(usize, usize)], len: usize) -> std::ops::Range<usize> {
    let after = kept.partition_point(|(was, _)| *was < orphan);
    let from = after.checked_sub(1).map_or(0, |i| kept[i].1);
    let to = kept.get(after).map_or(len, |(_, at)| at + 1).min(len);
    let to = to.max(from);
    if to - from > A_RESEGMENTATION_IS_LOCAL {
        return from..from;
    }
    from..to
}

impl Counts {
    pub fn absorb(&mut self, other: Counts) {
        self.works += other.works;
        self.segments += other.segments;
        self.headings += other.headings;
        self.empty_works += other.empty_works;
        self.malformed_ids += other.malformed_ids;
    }
}

/// Read one work from whichever corpus supplies it, as a first import.
///
/// Prefer [`read_over`] anywhere the work might already be on the shelf: this
/// one hands out names from reading order, which is only right the first time.
///
/// # Errors
///
/// If the source file cannot be read or does not hold what its schema says.
pub fn read(work: &Work) -> Result<ImportedWork, ImportError> {
    read_with(work, &Previous::none())
}

/// Read one work, keeping every name the shelf at `root` already gave it.
///
/// This is what `girsa-import` calls. The extra cost is one read of the work's
/// own `segments.jsonl`, which is the file about to be overwritten anyway.
///
/// # Errors
///
/// If the source file cannot be read or does not hold what its schema says. A
/// shelf that will not read back is not an error: it is a work with no names
/// worth keeping, and it is counted rather than fatal.
pub fn read_over(root: &Path, work: &Work) -> Result<ImportedWork, ImportError> {
    read_with(work, &Previous::on_the_shelf(root, &work.slug))
}

fn read_with(work: &Work, previous: &Previous) -> Result<ImportedWork, ImportError> {
    let mut work = work.clone();
    let raw = match work.source {
        Source::Sefaria => {
            let (raw, version) = sefaria::read(&work)?;
            // Which printed edition this is, read out of the text file rather
            // than guessed — spec.md §13. Otzaria's is known without opening
            // anything, so the catalogue already set it.
            work.version = version;
            raw
        }
        Source::Otzaria => otzaria::read(&work)?,
        // Yours, re-read from the file itself — the same rule as everything
        // else here (spec.md §4.1: the file on disk is the truth).
        Source::Mine => mine::read(&work)?,
    };
    Ok(ImportedWork::assemble_after(work, raw, previous))
}

/// Why a work could not be read.
#[derive(Debug, thiserror::Error)]
pub enum ImportError {
    #[error("reading {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("{path}: {message}")]
    Malformed { path: String, message: String },
}

impl ImportError {
    /// Public because the link importer reads the same files this one wrote,
    /// and reports its failures in the same shape.
    pub fn io(path: &Path) -> impl Fn(std::io::Error) -> Self + '_ {
        move |source| Self::Io {
            path: path.display().to_string(),
            source,
        }
    }

    pub fn malformed(path: &Path, message: impl Into<String>) -> Self {
        Self::Malformed {
            path: path.display().to_string(),
            message: message.into(),
        }
    }
}

/// Where a work's files live under the corpus root.
///
/// A slug carries `/` for a volume — `shulchan-arukh/orach-chayim` — and that
/// becomes a directory, so the shelf on disk reads the way the shelf in the app
/// does. Hebrew slugs are directory names too; every filesystem the three
/// target platforms use has been UTF-8-safe for a decade.
#[must_use]
pub fn work_dir(root: &Path, slug: &str) -> PathBuf {
    slug_dir(&root.join("works"), slug)
}

/// A slug as a directory under any base.
///
/// `girsa-link` puts a work's edges at `corpus/links/<slug>/`, mirroring
/// `corpus/works/<slug>/`, and the sanitizing a slug needs to survive being a
/// Windows path has to be identical in both — a second copy of it would drift
/// and the two halves of a sefer would stop lining up.
#[must_use]
pub fn slug_dir(base: &Path, slug: &str) -> PathBuf {
    let mut path = base.to_path_buf();
    for part in slug.split('/') {
        path.push(sanitize_component(part));
    }
    path
}

/// Make a path component Windows will accept, reversibly enough to debug.
///
/// The same problem `fetch` has, from the other end: a Hebrew title is fine,
/// but a work whose title carries `?` or `"` — Sefaria has three — cannot be a
/// directory on Windows at any path.
fn sanitize_component(part: &str) -> String {
    const FORBIDDEN: [char; 9] = ['<', '>', ':', '"', '\\', '|', '?', '*', '/'];
    let mut out = String::with_capacity(part.len());
    for c in part.chars() {
        if FORBIDDEN.contains(&c) || (c as u32) < 0x20 {
            out.push_str(&format!("%{:02X}", c as u32));
        } else {
            out.push(c);
        }
    }
    while out.ends_with(' ') || out.ends_with('.') {
        let last = out.pop().unwrap_or('.');
        out.push_str(&format!("%{:02X}", last as u32));
    }
    if out.is_empty() {
        out.push_str("%00");
    }
    out
}

/// Write a work: its metadata, its segments one per line, and where the names
/// that are no longer live went.
///
/// # Why the third file is deleted rather than written empty
///
/// A work with nothing redirected has no `redirects.jsonl`, and one that stops
/// having anything redirected loses the one it had. Leaving a stale file would
/// be worse than having none: `Previous` reads it, and a row saying a name was
/// cut when it is live again would send a reader to records that no longer
/// exist. The slot in the format is [`read_back`]'s to know about, not the
/// filesystem's.
///
/// # Errors
///
/// If the directory cannot be created or a file cannot be written.
pub fn write(root: &Path, imported: &ImportedWork) -> Result<(), ImportError> {
    let dir = work_dir(root, &imported.work.slug);
    fs::create_dir_all(&dir).map_err(ImportError::io(&dir))?;

    let meta_path = dir.join("work.json");
    let meta = serde_json::to_vec_pretty(&imported.work)
        .map_err(|e| ImportError::malformed(&meta_path, e.to_string()))?;
    fs::write(&meta_path, meta).map_err(ImportError::io(&meta_path))?;

    let segments_path = dir.join("segments.jsonl");
    let mut body = String::new();
    for segment in &imported.segments {
        let line = serde_json::to_string(segment)
            .map_err(|e| ImportError::malformed(&segments_path, e.to_string()))?;
        body.push_str(&line);
        body.push('\n');
    }
    fs::write(&segments_path, body).map_err(ImportError::io(&segments_path))?;

    let redirects_path = dir.join(REDIRECTS);
    if imported.redirects.is_empty() {
        if redirects_path.exists() {
            fs::remove_file(&redirects_path).map_err(ImportError::io(&redirects_path))?;
        }
        return Ok(());
    }
    let mut body = String::new();
    for redirect in &imported.redirects {
        let line = serde_json::to_string(redirect)
            .map_err(|e| ImportError::malformed(&redirects_path, e.to_string()))?;
        body.push_str(&line);
        body.push('\n');
    }
    fs::write(&redirects_path, body).map_err(ImportError::io(&redirects_path))
}

/// Where the names that are no longer live say they went.
///
/// Beside `segments.jsonl`, one row per name, the same shape and the same
/// rules: the row carries the name rather than implying it from its position.
pub const REDIRECTS: &str = "redirects.jsonl";

/// Put one work in your own catalogue — `personal/works/index.jsonl`.
///
/// The whole file is rewritten rather than appended to. W8 shipped an importer
/// that opened its shards in append mode and doubled the graph on a second run;
/// the same mistake here would put a sefer on the shelf twice.
///
/// Two callers: a file you dropped on the window ([`mine::add`]) and a note you
/// wrote (`girsa-note`, W27). One implementation, because the second copy of
/// this is the one that appends.
///
/// # Errors
///
/// If the personal layer cannot be written.
pub fn catalogue(personal: &Path, work: &Work) -> Result<(), ImportError> {
    let path = personal.join("works/index.jsonl");
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir).map_err(ImportError::io(dir))?;
    }
    let existing = fs::read_to_string(&path).unwrap_or_default();
    let mut body = String::new();
    for line in existing.lines().filter(|l| !l.trim().is_empty()) {
        let same = serde_json::from_str::<Work>(line).is_ok_and(|w| w.slug == work.slug);
        if !same {
            body.push_str(line);
            body.push('\n');
        }
    }
    let line =
        serde_json::to_string(work).map_err(|e| ImportError::malformed(&path, e.to_string()))?;
    body.push_str(&line);
    body.push('\n');
    fs::write(&path, body).map_err(ImportError::io(&path))
}

/// Take one back out of your catalogue. `false` if it was not in it.
///
/// # Errors
///
/// If the personal layer cannot be written.
pub fn uncatalogue(personal: &Path, slug: &str) -> Result<bool, ImportError> {
    let path = personal.join("works/index.jsonl");
    let Ok(existing) = fs::read_to_string(&path) else {
        return Ok(false);
    };
    let mut body = String::new();
    let mut gone = false;
    for line in existing.lines().filter(|l| !l.trim().is_empty()) {
        if serde_json::from_str::<Work>(line).is_ok_and(|w| w.slug == slug) {
            gone = true;
            continue;
        }
        body.push_str(line);
        body.push('\n');
    }
    if gone {
        fs::write(&path, body).map_err(ImportError::io(&path))?;
    }
    Ok(gone)
}

/// A work's segment ids, in reading order, without lexing its text.
///
/// The ids are what every derived artifact is keyed on and the text is 99.7% of
/// the bytes. `serde_json::from_str` into an `id`-only struct still walks every
/// escape of a segment that reaches 1,275,307 characters, so *skipping the
/// field* costs the same as reading it. This does not: `id` is the first field
/// of every line `write` produces, so the answer is between byte 7 and the next
/// quote.
///
/// A line that is not that shape falls back to the parser rather than being
/// dropped. Being fast is not a reason to be one segment short.
///
/// # Errors
///
/// If the file is missing, or a line has no readable id. A missing id fails the
/// read rather than being skipped — an ordered list silently one entry short
/// shifts every position after it, and positions are what the caller wanted.
pub fn ordered_ids(root: &Path, slug: &str) -> Result<Vec<SegmentId>, ImportError> {
    const OPENING: &str = "{\"id\":\"";

    let path = work_dir(root, slug).join("segments.jsonl");
    let body = fs::read_to_string(&path).map_err(ImportError::io(&path))?;
    let mut ids = Vec::new();
    for line in body.lines().filter(|l| !l.trim().is_empty()) {
        let text = match line.strip_prefix(OPENING).and_then(|rest| {
            // A segment id has no quote and no backslash in it — it is
            // `girsa:<slug>/<path>#<ordinal>` and every part of that is
            // constrained by `SegmentId`'s own parser. So the next quote is
            // the end of the field and not an escape.
            let end = rest.find('"')?;
            (!rest[..end].contains('\\')).then(|| rest[..end].to_string())
        }) {
            Some(text) => text,
            None => {
                #[derive(serde::Deserialize)]
                struct IdOnly {
                    id: String,
                }
                serde_json::from_str::<IdOnly>(line)
                    .map_err(|e| ImportError::malformed(&path, e.to_string()))?
                    .id
            }
        };
        let id: SegmentId = text.parse().map_err(|e: crate::segment::SegmentIdError| {
            ImportError::malformed(&path, e.to_string())
        })?;
        ids.push(id);
    }
    Ok(ids)
}

/// Read back what [`write`] wrote.
///
/// # Errors
///
/// If the files are missing or a record does not parse. A record that does not
/// parse fails the read rather than being skipped: a segments file silently
/// one segment short is the failure this whole design is arranged against.
pub fn read_back(root: &Path, slug: &str) -> Result<ImportedWork, ImportError> {
    let dir = work_dir(root, slug);
    let meta_path = dir.join("work.json");
    let meta = fs::read_to_string(&meta_path).map_err(ImportError::io(&meta_path))?;
    let work: Work = serde_json::from_str(&meta)
        .map_err(|e| ImportError::malformed(&meta_path, e.to_string()))?;

    let segments_path = dir.join("segments.jsonl");
    let body = fs::read_to_string(&segments_path).map_err(ImportError::io(&segments_path))?;
    let mut segments = Vec::new();
    for line in body.lines().filter(|l| !l.trim().is_empty()) {
        let segment: Segment = serde_json::from_str(line)
            .map_err(|e| ImportError::malformed(&segments_path, e.to_string()))?;
        segments.push(segment);
    }
    // A work imported by a build older than the redirect table has no such file,
    // and that is not a failure — it is a work nothing has redirected yet. The
    // 7,189 directories already on disk read as exactly that.
    let redirects_path = dir.join(REDIRECTS);
    let mut redirects = Vec::new();
    if let Ok(body) = fs::read_to_string(&redirects_path) {
        for line in body.lines().filter(|l| !l.trim().is_empty()) {
            let redirect: Redirect = serde_json::from_str(line)
                .map_err(|e| ImportError::malformed(&redirects_path, e.to_string()))?;
            redirects.push(redirect);
        }
    }

    // Measured on the way back in, so `read_back` reports what is on disk rather
    // than what the last import happened to do — which is what makes it usable as
    // a check over a corpus imported by an older build.
    let mut oversized = oversized::Tally::default();
    for segment in &segments {
        oversized.saw(
            &segment.id.to_string(),
            segment.text.chars().count(),
            &work.slug,
        );
    }
    Ok(ImportedWork {
        work,
        segments,
        oversized,
        redirects,
        // Not a measurement of what is on disk. This says what the *last import*
        // kept, and reading a work back is not an import — reporting a number
        // here would be reporting one nothing computed.
        continuity: continuity::Continuity::default(),
    })
}

#[cfg(test)]
mod tests {
    // A panic in a test is a failure report. The workspace denies these in
    // library code, where a panic would take the reader's window with it.
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;
    use crate::work::Source;

    fn work() -> Work {
        Work {
            slug: "shulchan-arukh/orach-chayim".into(),
            he_title: "שולחן ערוך, אורח חיים".into(),
            en_title: "Shulchan Arukh, Orach Chayim".into(),
            categories: vec!["Halakhah".into()],
            source: Source::Sefaria,
            origin: PathBuf::from("merged.json"),
            schema: None,
            author: None,
            era: None,
            comp_date: None,
            version: None,
            he_sections: Vec::new(),
            commentary_on: Vec::new(),
        }
    }

    fn raw(path: &[&str], text: &str) -> RawSegment {
        RawSegment {
            path: path.iter().map(|p| (*p).to_string()).collect(),
            kind: SegmentKind::Text,
            text: text.to_string(),
        }
    }

    #[test]
    fn ordinals_are_handed_out_in_reading_order_starting_at_one() {
        let imported = ImportedWork::assemble(
            work(),
            vec![
                raw(&["1", "1"], "יתגבר כארי"),
                raw(&["1", "2"], "ולא יתבייש"),
                raw(&["2", "1"], "המשכים"),
            ],
        );
        let ids: Vec<String> = imported.segments.iter().map(|s| s.id.to_string()).collect();
        assert_eq!(
            ids,
            [
                "girsa:shulchan-arukh/orach-chayim/1:1#1",
                "girsa:shulchan-arukh/orach-chayim/1:2#2",
                "girsa:shulchan-arukh/orach-chayim/2:1#3",
            ]
        );
    }

    #[test]
    fn a_segments_file_names_each_segment_rather_than_counting_lines() {
        // The property that keeps T1 out of the storage format. Shuffle the
        // file and every id still names the same words, because the id is in
        // the line rather than being the line's position.
        let dir = std::env::temp_dir().join("girsa-import-test-idnames");
        let _ = fs::remove_dir_all(&dir);
        let imported = ImportedWork::assemble(
            work(),
            vec![
                raw(&["1", "1"], "first"),
                raw(&["1", "2"], "second"),
                raw(&["1", "3"], "third"),
            ],
        );
        write(&dir, &imported).expect("writes");

        let path = work_dir(&dir, "shulchan-arukh/orach-chayim").join("segments.jsonl");
        let body = fs::read_to_string(&path).expect("reads");
        let mut lines: Vec<&str> = body.lines().collect();
        lines.reverse();
        fs::write(&path, lines.join("\n")).expect("rewrites");

        let back = read_back(&dir, "shulchan-arukh/orach-chayim").expect("reads back");
        let found = back
            .segments
            .iter()
            .find(|s| s.id.to_string().ends_with("/1:2#2"))
            .map(|s| s.text.clone());
        assert_eq!(found.as_deref(), Some("second"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn counts_tell_headings_from_text() {
        let imported = ImportedWork::assemble(
            work(),
            vec![
                RawSegment {
                    path: vec!["1".into()],
                    kind: SegmentKind::Heading,
                    text: "סימן א".into(),
                },
                raw(&["1", "1"], "יתגבר כארי"),
            ],
        );
        let counts = imported.counts();
        assert_eq!(counts.segments, 2);
        assert_eq!(counts.headings, 1);
        assert_eq!(counts.malformed_ids, 0);
    }
}
