//! Build the resolver's lexicon out of Sefaria's schemas.
//!
//! ```sh
//! cargo run --release -p girsa-corpus --example build-lexicon -- \
//!     corpus/sefaria/schemas corpus/lexicon.tsv
//! ```
//!
//! spec.md §4.3 says the resolver is *"seeded from Sefaria's `titles` and
//! `match_templates`, which is most of the lexicon for free"*. This is the step
//! that collects it: every way each of 6,595 works is written, in both
//! languages, from the files that already list them.
//!
//! `Shulchan_Arukh,_Orach_Chayim.json` alone contributes 44 spellings.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use serde_json::Value;

// **The** `slug_of`, not one of two.
//
// This example carried its own copy — byte-identical, thirty-seven lines —
// beside a doc comment on the original saying *"this is the same function the
// lexicon is built with… a second implementation that drifted by a hyphen would
// resolve citations onto works that do not exist."* The lexicon maps a citation
// onto a slug and the importer names segments after one; they have to be the
// same letters or a resolved ref points at a work that is not on the shelf.
//
// The comment was right and the copy was under it.
use girsa_corpus::work::slug_of;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let (Some(schema_dir), Some(out)) = (args.next(), args.next()) else {
        eprintln!("usage: build-lexicon <schemas-dir> <output.tsv>");
        std::process::exit(2);
    };

    // variant → slug, and slug → (he title, en title). BTreeMap so the output
    // is byte-identical between runs and a regenerated lexicon shows an empty
    // diff when nothing changed.
    let mut rows: BTreeMap<(String, String), (String, String)> = BTreeMap::new();
    let mut works = 0usize;
    let mut skipped = 0usize;

    let mut entries: Vec<_> = fs::read_dir(&schema_dir)?.flatten().collect();
    entries.sort_by_key(std::fs::DirEntry::file_name);

    for entry in entries {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "json") {
            continue;
        }
        let Ok(text) = fs::read_to_string(&path) else {
            skipped += 1;
            continue;
        };
        let Ok(schema): Result<Value, _> = serde_json::from_str(&text) else {
            skipped += 1;
            continue;
        };

        let Some(en_title) = schema.get("title").and_then(Value::as_str) else {
            skipped += 1;
            continue;
        };
        let he_title = schema
            .get("heTitle")
            .and_then(Value::as_str)
            .unwrap_or(en_title);
        let categories = string_list(schema.get("categories"));
        let slug = slug_of(en_title, &categories);
        works += 1;

        for variant in variants_of(&schema, en_title, he_title) {
            let variant = clean(&variant);
            if variant.is_empty() {
                continue;
            }
            rows.insert(
                (variant, slug.clone()),
                (he_title.to_string(), en_title.to_string()),
            );
        }
    }

    let mut tsv = String::new();
    tsv.push_str(
        "# girsa-ref lexicon. GENERATED by girsa-corpus/examples/build-lexicon.rs\n\
         # from Sefaria's schemas. Do not hand-edit — regenerate.\n\
         # variant\tslug\the-title\ten-title\n",
    );
    for ((variant, slug), (he, en)) in &rows {
        tsv.push_str(&format!("{variant}\t{slug}\t{he}\t{en}\n"));
    }
    fs::write(Path::new(&out), tsv)?;

    eprintln!("{works} works, {} spellings -> {out}", rows.len());
    if skipped > 0 {
        // Loud. A schema that failed to parse is a sefer whose citations will
        // not resolve, and a silent count of those is how a resolver ends up
        // mysteriously bad at one shelf.
        eprintln!("SKIPPED {skipped} schema files that would not parse");
    }
    Ok(())
}

/// Every spelling a schema offers.
fn variants_of(schema: &Value, en_title: &str, he_title: &str) -> Vec<String> {
    let mut out = vec![en_title.to_string(), he_title.to_string()];
    out.extend(string_list(schema.get("titleVariants")));
    out.extend(string_list(schema.get("heTitleVariants")));

    // The nested node carries its own `titles`, as `{text, lang}` pairs. This
    // is where the 44 spellings of Orach Chayim actually live.
    if let Some(titles) = schema.pointer("/schema/titles").and_then(Value::as_array) {
        out.extend(
            titles
                .iter()
                .filter_map(|t| t.get("text").and_then(Value::as_str))
                .map(str::to_string),
        );
    }
    out
}

fn string_list(v: Option<&Value>) -> Vec<String> {
    v.and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

/// Strip the markup Sefaria's title lists carry.
///
/// Several variants arrive wrapped in `<i>…</i>` — the transliterated ones,
/// `<i>Shulḥan Arukh, Oraḥ Ḥayyim</i>`. Left in, the tag becomes part of the
/// spelling and the variant matches nothing.
fn clean(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for c in s.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            '\t' | '\n' | '\r' => out.push(' '),
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    out.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_volume_title_becomes_a_work_path() {
        assert_eq!(
            slug_of("Shulchan Arukh, Orach Chayim", &[]),
            "shulchan-arukh/orach-chayim"
        );
    }

    #[test]
    fn a_masechta_says_which_talmud_it_is_from() {
        let bavli = ["Talmud".into(), "Bavli".into(), "Seder Zeraim".into()];
        let yerushalmi = ["Talmud".into(), "Yerushalmi".into()];
        assert_eq!(slug_of("Berakhot", &bavli), "bavli/berakhot");
        assert_eq!(
            slug_of("Jerusalem Talmud Berakhot", &yerushalmi),
            "yerushalmi/jerusalem-talmud-berakhot"
        );
    }

    #[test]
    fn markup_around_a_title_is_not_part_of_the_spelling() {
        assert_eq!(
            clean("<i>Shulḥan Arukh, Oraḥ Ḥayyim</i>"),
            "Shulḥan Arukh, Oraḥ Ḥayyim"
        );
    }
}
