//! Measure the resolver against real citations, and report the number.
//!
//! ```sh
//! cargo run --release -p girsa-corpus --example measure-resolver -- \
//!     corpus/lexicon.tsv corpus/sefaria/links "$OTZARIA/links"
//! ```
//!
//! BUILDER.md W3 asks for a regression corpus of *real* citations, mined from
//! the corpus rather than invented, and for ≥95% exact resolution with every
//! miss classified as `Ambiguous` rather than wrong.
//!
//! # Where the citations come from
//!
//! Inventing test citations measures how well the resolver handles citations
//! its author already had in mind. These are neither invented nor sampled by
//! hand:
//!
//! - **Sefaria's `links*.csv`** are addressed by canonical citation —
//!   `Sanhedrin 74b:9`, `Mishnah Peah 6:6` — several million of them, produced
//!   by Sefaria for the whole corpus.
//! - **Otzaria's `*_links.json`** carry `heRef_2`, the same links written in
//!   Hebrew as a person would — `סליחות נוסח אשכנז ליטא, ליום ראשון, ג, יא`.
//!
//! Between them that is the English half and the Hebrew half of the problem,
//! at a scale no hand-written fixture reaches.
//!
//! # What counts as a pass
//!
//! Exact only. An `Ambiguous` result is **not** counted as a success — it is
//! the honest answer to a genuinely ambiguous citation, and it is reported
//! separately so the two failure modes stay distinguishable. Wrong is never
//! acceptable; unresolved is a gap; ambiguous is correct behaviour that still
//! costs the reader a click.

use std::fs;
use std::path::Path;

use girsa_ref::{resolve, Lexicon, Resolution};

/// Enough rows for the percentage to be stable, few enough to run in seconds.
const SAMPLE_PER_SOURCE: usize = 20_000;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let Some(lexicon_path) = args.next() else {
        eprintln!("usage: measure-resolver <lexicon.tsv> <sefaria-links-dir> [otzaria-links-dir]");
        std::process::exit(2);
    };
    let sefaria_links = args.next();
    let otzaria_links = args.next();

    let lexicon = Lexicon::from_tsv(&fs::read_to_string(&lexicon_path)?);
    eprintln!(
        "lexicon: {} works, {} spellings\n",
        lexicon.len(),
        lexicon.variant_count()
    );

    // A fourth argument writes the sampled citations out, so the same real
    // strings can be committed as a fixture and the measurement becomes a test
    // rather than something someone has to remember to run.
    let dump_to = args.next();
    let mut dump = String::new();

    if let Some(dir) = sefaria_links {
        let citations = sefaria_citations(Path::new(&dir))?;
        report(
            "Sefaria links*.csv (English, canonical)",
            &lexicon,
            &citations,
        );
        append_sample(&mut dump, "sefaria", &citations);
    }
    if let Some(dir) = otzaria_links {
        let citations = otzaria_citations(Path::new(&dir))?;
        report("Otzaria heRef (Hebrew, as printed)", &lexicon, &citations);
        append_sample(&mut dump, "otzaria", &citations);
    }

    if let Some(path) = dump_to {
        let header = "# girsa-ref citation regression corpus. GENERATED by\n\
                      # girsa-corpus/examples/measure-resolver.rs from Sefaria's link CSVs and\n\
                      # Otzaria's heRefs. Every line is a citation that genuinely appears in the\n\
                      # corpus. Do not hand-edit — regenerate.\n\
                      # source\tcitation\n";
        fs::write(&path, format!("{header}{dump}"))?;
        eprintln!("wrote the sampled citations to {path}");
    }
    Ok(())
}

/// Spread the sample across the whole run rather than taking the first N, which
/// would all come from one sefer and one shelf.
const FIXTURE_ROWS_PER_SOURCE: usize = 1500;

fn append_sample(dump: &mut String, source: &str, citations: &[String]) {
    let stride = (citations.len() / FIXTURE_ROWS_PER_SOURCE).max(1);
    let mut seen = std::collections::BTreeSet::new();
    for citation in citations
        .iter()
        .step_by(stride)
        .take(FIXTURE_ROWS_PER_SOURCE)
    {
        let one_line = citation.replace(['\t', '\n', '\r'], " ");
        if seen.insert(one_line.clone()) {
            dump.push_str(&format!("{source}\t{one_line}\n"));
        }
    }
}

fn report(source: &str, lexicon: &Lexicon, citations: &[String]) {
    let mut exact = 0usize;
    let mut ambiguous = 0usize;
    let mut unresolved: Vec<&String> = Vec::new();

    for citation in citations {
        match resolve(lexicon, citation) {
            Resolution::Exact(_) => exact += 1,
            Resolution::Ambiguous(_) => ambiguous += 1,
            Resolution::Unresolved => unresolved.push(citation),
        }
    }

    let total = citations.len().max(1);
    let pct = |n: usize| (n as f64) * 100.0 / (total as f64);
    println!("== {source}");
    println!("   {total} citations");
    println!("   exact       {exact:>7}  {:>5.1}%", pct(exact));
    println!("   ambiguous   {ambiguous:>7}  {:>5.1}%", pct(ambiguous));
    println!(
        "   unresolved  {:>7}  {:>5.1}%",
        unresolved.len(),
        pct(unresolved.len())
    );
    if !unresolved.is_empty() {
        println!("   a sample of what did not resolve:");
        for c in unresolved.iter().take(12) {
            println!("     {c}");
        }
    }
    println!();
}

/// `Citation 1` and `Citation 2` out of the link CSVs.
fn sefaria_citations(dir: &Path) -> std::io::Result<Vec<String>> {
    let mut out = Vec::new();
    let mut files: Vec<_> = fs::read_dir(dir)?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "csv"))
        .collect();
    files.sort();

    for path in files {
        if out.len() >= SAMPLE_PER_SOURCE {
            break;
        }
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        for line in text.lines().skip(1) {
            if out.len() >= SAMPLE_PER_SOURCE {
                break;
            }
            let fields = csv_fields(line);
            for citation in fields.iter().take(2) {
                if !citation.trim().is_empty() {
                    out.push(citation.clone());
                }
            }
        }
    }
    Ok(out)
}

/// `heRef_2` out of Otzaria's per-sefer link files.
fn otzaria_citations(dir: &Path) -> std::io::Result<Vec<String>> {
    let mut out = Vec::new();
    let mut files: Vec<_> = fs::read_dir(dir)?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    files.sort();

    // Stride across the shelves rather than taking the first few files, which
    // would all be one letter of the alphabet and one kind of sefer.
    let stride = (files.len() / 400).max(1);
    for path in files.iter().step_by(stride) {
        if out.len() >= SAMPLE_PER_SOURCE {
            break;
        }
        let Ok(text) = fs::read_to_string(path) else {
            continue;
        };
        let Ok(value): Result<serde_json::Value, _> = serde_json::from_str(&text) else {
            continue;
        };
        let Some(rows) = value.as_array() else {
            continue;
        };
        for row in rows {
            if out.len() >= SAMPLE_PER_SOURCE {
                break;
            }
            if let Some(he_ref) = row.get("heRef_2").and_then(serde_json::Value::as_str) {
                // These arrive with trailing commas and doubled spaces —
                // `"סליחות נוסח אשכנז ליטא, ליום ראשון,  ג, יא,"`. The grime is
                // the corpus's, and stripping it is the importer's job, not a
                // reason to score the resolver on a string nobody would type.
                let cleaned = he_ref.trim().trim_end_matches(',').trim();
                if !cleaned.is_empty() {
                    out.push(cleaned.to_string());
                }
            }
        }
    }
    Ok(out)
}

/// Split one CSV line, honouring quotes.
///
/// Sefaria's citations contain commas — `"A Dictionary of the Talmud, אֱגוֹד 1"`
/// — so splitting on the comma alone tears the title in half and every row
/// scores as unresolved for a reason that has nothing to do with the resolver.
fn csv_fields(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            '"' if in_quotes && chars.peek() == Some(&'"') => {
                current.push('"');
                chars.next();
            }
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => fields.push(std::mem::take(&mut current)),
            _ => current.push(c),
        }
    }
    fields.push(current);
    fields
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_citation_containing_a_comma_survives_the_csv() {
        let line = "\"A Dictionary of the Talmud, אֱגוֹד 1\",Mishnah Peah 6:6,quotation";
        let fields = csv_fields(line);
        assert_eq!(fields[0], "A Dictionary of the Talmud, אֱגוֹד 1");
        assert_eq!(fields[1], "Mishnah Peah 6:6");
        assert_eq!(fields[2], "quotation");
    }
}
