//! The shelf itself: what is on it, written the way the download writes it.
//!
//! Every Sefaria work here becomes a `merged.json` and a `schemas/<slug>.json`,
//! and [`girsa_corpus::import::sefaria::read`] walks them. Every Otzaria work
//! becomes a `.txt` with `<h1>`/`<h2>` headings, and
//! [`girsa_corpus::import::otzaria::read`] parses them. Nothing here writes a
//! segment, an ordinal or an address — those are what is being tested.
//!
//! # Why the text is real
//!
//! Berakhot 2a says מאימתי, Bereishis 1:1 says בראשית ברא, and Orach Chayim 1:1
//! says יתגבר כארי, because tests assert on those words and a fixture full of
//! `lorem ipsum` turns every one of those assertions into a check that this file
//! is spelled the way this file is spelled. Where a sefer needs to be long rather
//! than quoted — Bava Metzia has to reach daf 59b, Orach Chayim has to reach
//! siman 58 — the intervening sections are written as **empty arrays**, which is
//! what Sefaria itself writes for a section it has no text for. An empty section
//! produces no segments and still holds the address open, so `נח:א` resolves
//! without this file inventing fifty-six simanim of halacha.
//!
//! # Why nikud is not uniform
//!
//! Mishnah Berakhot is menukad and the Rambam's commentary on it is bare. That is
//! the pair spec.md §2.1 gives as its example of inconsistent coverage, and
//! `known_good_lookup` compares the two ends of one link through
//! `girsa_hebrew::normalize` because of it. Tidy the nikud and that test still
//! passes and stops checking anything.

use std::path::Path;

use girsa_corpus::import::{self, Previous};
use girsa_corpus::work::{BaseText, Mapping, Source, Work};
use serde_json::{json, Value};

/// One sefer, as the download holds it.
pub struct Sefer {
    pub slug: String,
    pub he: String,
    pub en: String,
    pub categories: Vec<String>,
    pub era: Option<String>,
    pub comp_date: Option<String>,
    pub author: Option<String>,
    /// The seforim this one declares itself a commentary on, the way Sefaria's
    /// `base_text_titles` declares them — never guessed from `X on Y`, which is
    /// how `Rashi on Berakhot` gets attached to the Yerushalmi masechta of the
    /// same name (BUILDER.md rule 6).
    pub base: Vec<String>,
    /// Spellings a citation might use, beyond the two titles. `שו"ע או"ח` is one
    /// of these and it is the reason the abbreviation tests can run.
    pub variants: Vec<String>,
    pub body: Body,
}

/// What the source file for this sefer looks like.
pub enum Body {
    /// A `merged.json` with a `schema` node beside it.
    Sefaria {
        schema: Value,
        text: Value,
        he_sections: Vec<String>,
        /// What `merged.json` names as the editions it was merged from, so
        /// `version_of` has something to read and spec.md §13's provenance is
        /// carried by the real code rather than set by hand.
        edition: String,
    },
    /// An Otzaria `.txt`, headings and all.
    Otzaria { txt: String },
}

/// Write the whole shelf under `root` and leave it importable.
///
/// # Panics
///
/// If the fixture cannot be written or a work will not import. Either is a
/// broken fixture, and a test standing on one reports a failure that has nothing
/// to do with what it was asserting.
pub fn build(root: &Path) {
    let seforim = shelf();
    let mut works = Vec::new();

    for sefer in &seforim {
        let work = lay_down(root, sefer);
        // The real importer, over the real source file. `read` rather than
        // `read_over`: a fixture is always a first import, and there is no
        // earlier promise to keep.
        let imported = import::read(&work).unwrap_or_else(|e| panic!("{}: {e}", sefer.slug));
        import::write(root, &imported).unwrap_or_else(|e| panic!("{}: {e}", sefer.slug));
        // The version comes back off `merged.json` through the importer, so the
        // catalogue carries what the file said rather than what this crate did.
        works.push(imported.work);
    }

    let mut index = String::new();
    for work in &works {
        let line = serde_json::to_string(work).expect("a work serializes");
        index.push_str(&line);
        index.push('\n');
    }
    crate::put(&root.join("works/index.jsonl"), &index);
    crate::put(&root.join("lexicon.tsv"), &lexicon(&seforim));
    // Written empty rather than left out: `girsa-link-import` treats a missing
    // Otzaria lexicon as a survivable loss and says so on stderr, and a fixture
    // that made it print that every run would be teaching everyone to ignore it.
    crate::put(
        &root.join("lexicon-otzaria.tsv"),
        "# GENERATED by girsa-fixture — the Otzaria-only works.\n",
    );
}

/// Re-import a work that is already on the shelf, keeping the names it has.
///
/// This is [`import::read_over`] with the source file rewritten first, which is
/// what an upstream re-segmentation actually is: the same work, a different
/// `merged.json`, run through the same importer a second time. `continuity` is
/// the half of §3 that only exists on the second run, and before this there was
/// no way to reach it from a test without a corpus and a Sefaria release.
///
/// # Panics
///
/// If the work will not re-import.
pub fn reimport(root: &Path, sefer: &Sefer) -> import::ImportedWork {
    let work = lay_down(root, sefer);
    let previous = Previous::on_the_shelf(root, &work.slug);
    let raw = match import::read_over(root, &work) {
        Ok(imported) => imported,
        Err(e) => panic!("{}: {e}", sefer.slug),
    };
    debug_assert!(!previous.is_empty() || raw.continuity.kept == 0);
    import::write(root, &raw).unwrap_or_else(|e| panic!("{}: {e}", sefer.slug));
    raw
}

/// Write one sefer's source file and describe it as a [`Work`].
fn lay_down(root: &Path, sefer: &Sefer) -> Work {
    let commentary_on = sefer
        .base
        .iter()
        .map(|slug| BaseText {
            slug: slug.clone(),
            mapping: Mapping::ManyToOne,
        })
        .collect();

    match &sefer.body {
        Body::Sefaria {
            schema,
            text,
            he_sections,
            edition,
        } => {
            let dir = root.join("sefaria").join(&sefer.slug);
            let origin = dir.join("merged.json");
            let schema_path = root
                .join("schemas")
                .join(format!("{}.json", flat(&sefer.slug)));
            crate::put(
                &origin,
                &serde_json::to_string(&json!({
                    "text": text,
                    "versionTitle": edition,
                    "versions": [[edition, "https://www.sefaria.org/"]],
                    "versionSource": "https://www.sefaria.org/",
                }))
                .expect("merged.json serializes"),
            );
            // The authoritative schema is the one in `schemas/`, which is where
            // the importer looks first — so that is where the fixture puts it,
            // rather than relying on `merged.json`'s sometimes-copy.
            crate::put(
                &schema_path,
                &serde_json::to_string(&json!({ "schema": schema })).expect("a schema serializes"),
            );
            Work {
                slug: sefer.slug.clone(),
                he_title: sefer.he.clone(),
                en_title: sefer.en.clone(),
                categories: sefer.categories.clone(),
                order: Vec::new(),
                source: Source::Sefaria,
                origin,
                schema: Some(schema_path),
                he_sections: he_sections.clone(),
                author: sefer.author.clone(),
                era: sefer.era.clone(),
                comp_date: sefer.comp_date.clone(),
                // Read off `merged.json` by the importer, not set here.
                version: None,
                commentary_on,
            }
        }
        Body::Otzaria { txt } => {
            let origin = root
                .join("otzaria")
                .join(format!("{}.txt", flat(&sefer.slug)));
            crate::put(&origin, txt);
            Work {
                slug: sefer.slug.clone(),
                he_title: sefer.he.clone(),
                en_title: sefer.en.clone(),
                categories: sefer.categories.clone(),
                order: Vec::new(),
                source: Source::Otzaria,
                origin,
                schema: None,
                he_sections: Vec::new(),
                author: sefer.author.clone(),
                era: sefer.era.clone(),
                comp_date: sefer.comp_date.clone(),
                version: None,
                commentary_on,
            }
        }
    }
}

/// A slug as one path component, for the flat directories the download has.
fn flat(slug: &str) -> String {
    slug.replace('/', "_")
}

/// `variant \t slug \t he-title \t en-title`, the format `Lexicon::from_tsv`
/// reads and `girsa-import` writes.
fn lexicon(seforim: &[Sefer]) -> String {
    let mut out = String::from("# GENERATED by girsa-fixture.\n");
    for sefer in seforim {
        let mut variants = vec![sefer.he.clone(), sefer.en.clone()];
        variants.extend(sefer.variants.iter().cloned());
        for variant in variants {
            out.push_str(&format!(
                "{}\t{}\t{}\t{}\n",
                variant, sefer.slug, sefer.he, sefer.en
            ));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// The shelf
// ---------------------------------------------------------------------------

/// A jagged schema node, the common case — 5,493 of Sefaria's 6,595.
fn jagged(
    depth: usize,
    address_types: &[&str],
    he_sections: &[&str],
    lengths: Vec<usize>,
) -> Value {
    json!({
        "nodeType": "JaggedArrayNode",
        "depth": depth,
        "addressTypes": address_types,
        "heSectionNames": he_sections,
        "lengths": lengths,
    })
}

/// One Sefaria work, with the fields most of them share already filled in.
fn sefer(slug: &str, he: &str, en: &str, categories: &[&str], body: Body) -> Sefer {
    Sefer {
        slug: slug.to_string(),
        he: he.to_string(),
        en: en.to_string(),
        categories: categories.iter().map(|c| (*c).to_string()).collect(),
        era: None,
        comp_date: None,
        author: None,
        base: Vec::new(),
        variants: Vec::new(),
        body,
    }
}

impl Sefer {
    fn dated(mut self, era: &str, comp_date: &str) -> Self {
        self.era = Some(era.to_string());
        self.comp_date = Some(comp_date.to_string());
        self
    }

    fn on(mut self, base: &str) -> Self {
        self.base.push(base.to_string());
        self
    }

    fn also_called(mut self, variant: &str) -> Self {
        self.variants.push(variant.to_string());
        self
    }

    fn by(mut self, author: &str) -> Self {
        self.author = Some(author.to_string());
        self
    }
}

/// A Sefaria body: a schema, the text it describes, and the edition it is.
fn text(schema: Value, text: Value, he_sections: &[&str], edition: &str) -> Body {
    Body::Sefaria {
        schema,
        text,
        he_sections: he_sections.iter().map(|s| (*s).to_string()).collect(),
        edition: edition.to_string(),
    }
}

/// `n` empty sections, for holding an address open without inventing a text.
fn blanks(n: usize) -> Vec<Value> {
    vec![json!([]); n]
}

/// A flat array of amudim from `1a`, with `at` filled in.
///
/// Sefaria stores a masechta this way, so index 0 is daf 1a — which does not
/// exist — and index 2 is daf 2a, where every masechta begins. Read as an
/// integer every daf in Shas is off by a page and a half, which is exactly what
/// `berakhot_begins_at_daf_2a_and_not_at_daf_1` is about.
fn amudim(pages: usize, at: &[(usize, Value)]) -> Value {
    let mut out = blanks(pages);
    for (i, lines) in at {
        out[*i] = lines.clone();
    }
    Value::Array(out)
}

/// The index of a daf and amud in that flat array. `2a` is 2, `59b` is 117.
fn daf(number: usize, amud: char) -> usize {
    (number - 1) * 2 + usize::from(amud == 'b')
}

/// Every sefer on the fixture shelf.
///
/// Twenty-eight works, chosen so that between them they reach every assertion
/// the forty-three corpus-gated tests were making: a masechta with its Rashi and
/// Tosafos, a mishnah with its Rambam and Bartenura, the Shulchan Arukh with its
/// nosei keilim on the right volumes and not on the wrong ones, a chumash with
/// seven mefarshim, a branch schema, and one work from each corpus filed under
/// each corpus's own vocabulary for the same shelf.
#[must_use]
#[allow(clippy::too_many_lines)]
pub fn shelf() -> Vec<Sefer> {
    vec![
        // --- Shas -------------------------------------------------------
        sefer(
            "bavli/berakhot",
            "ברכות",
            "Berakhot",
            &["Talmud", "Bavli", "Seder Zeraim"],
            text(
                jagged(2, &["Talmud", "Integer"], &["דף", "שורה"], vec![3, 8]),
                amudim(
                    6,
                    &[
                        (
                            daf(2, 'a'),
                            json!([
                                "מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּעַרְבִית",
                                "מִשָּׁעָה שֶׁהַכֹּהֲנִים נִכְנָסִים לֶאֱכוֹל בִּתְרוּמָתָן",
                                "עַד סוֹף הָאַשְׁמוּרָה הָרִאשׁוֹנָה דִּבְרֵי רַבִּי אֱלִיעֶזֶר",
                                "וַחֲכָמִים אוֹמְרִים עַד חֲצוֹת",
                            ]),
                        ),
                        (
                            daf(2, 'b'),
                            json!(["מַאי שְׁנָא דְּתָנֵי בְּעַרְבִית בְּרֵישָׁא", "לִיתְנֵי דְּשַׁחֲרִית בְּרֵישָׁא",]),
                        ),
                        (
                            daf(3, 'a'),
                            json!([
                                "אָמַר רַבִּי אֱלִיעֶזֶר שָׁלֹשׁ מִשְׁמָרוֹת הָוֵי הַלַּיְלָה",
                                "וְעַל כׇּל מִשְׁמָר וּמִשְׁמָר יוֹשֵׁב הַקָּדוֹשׁ בָּרוּךְ הוּא",
                            ]),
                        ),
                    ],
                ),
                &["דף", "שורה"],
                "William Davidson Edition - Vocalized Aramaic",
            ),
        )
        .dated("A", "450 CE")
        .also_called("Berakhot")
        .also_called("מסכת ברכות"),
        // Rashi comments on 2a:1 and 2a:3 and on nothing in between. That gap is
        // the whole of `a_line_with_no_rashi_on_it_leaves_the_column_where_it_was`:
        // a pane that slid to the nearest comment would be showing the reader
        // Rashi on a different line with nothing to say it had moved.
        sefer(
            "bavli/rashi-on-berakhot",
            "רש\"י על ברכות",
            "Rashi on Berakhot",
            &["Talmud", "Bavli", "Rishonim on Talmud", "Rashi"],
            text(
                jagged(
                    3,
                    &["Talmud", "Integer", "Integer"],
                    &["דף", "שורה", ""],
                    vec![3, 8, 7],
                ),
                amudim(
                    6,
                    &[
                        (
                            daf(2, 'a'),
                            json!([
                                [
                                    "מאימתי קורין את שמע בערבית - ומאימתי הוי זמן שכיבה",
                                    "משעה שהכהנים נכנסין - כהנים שנטמאו"
                                ],
                                [],
                                ["עד סוף האשמורה הראשונה - שליש הלילה"],
                                [],
                            ]),
                        ),
                        (
                            daf(2, 'b'),
                            json!([["מאי שנא - מאי טעמא"], ["ליתני דשחרית ברישא - כסדר הכתוב"]]),
                        ),
                        (daf(3, 'a'), json!([["שלש משמרות - שלש חלקים"]])),
                    ],
                ),
                &["דף", "שורה", ""],
                "Vilna Edition",
            ),
        )
        .dated("RI", "1090 CE")
        .by("רש\"י")
        .on("bavli/berakhot"),
        sefer(
            "bavli/tosafot-on-berakhot",
            "תוספות על ברכות",
            "Tosafot on Berakhot",
            &["Talmud", "Bavli", "Rishonim on Talmud", "Tosafot"],
            text(
                jagged(
                    3,
                    &["Talmud", "Integer", "Integer"],
                    &["דף", "שורה", ""],
                    vec![3, 8, 2],
                ),
                amudim(
                    6,
                    &[
                        (
                            daf(2, 'a'),
                            json!([["מאימתי קורין - פירש\"י ואנן היכי קרינן"], [], [], []]),
                        ),
                        (daf(2, 'b'), json!([["ליתני דשחרית ברישא - וא\"ת והלא"]])),
                    ],
                ),
                &["דף", "שורה", ""],
                "Vilna Edition",
            ),
        )
        .dated("RI", "1200 CE")
        .on("bavli/berakhot"),
        // Reaches daf 59b, so `בבא מציעא נט:` has a place to settle on. The
        // hundred and sixteen amudim before it are empty arrays, which is what
        // Sefaria writes for a section it has no text for.
        sefer(
            "bavli/bava-metzia",
            "בבא מציעא",
            "Bava Metzia",
            &["Talmud", "Bavli", "Seder Nezikin"],
            text(
                jagged(2, &["Talmud", "Integer"], &["דף", "שורה"], vec![59, 2]),
                amudim(
                    118,
                    &[(
                        daf(59, 'b'),
                        json!([
                            "בְּאוֹתוֹ הַיּוֹם הֵשִׁיב רַבִּי אֱלִיעֶזֶר כׇּל תְּשׁוּבוֹת שֶׁבָּעוֹלָם",
                            "יָצְאָה בַּת קוֹל וְאָמְרָה מַה לָּכֶם אֵצֶל רַבִּי אֱלִיעֶזֶר",
                        ]),
                    )],
                ),
                &["דף", "שורה"],
                "William Davidson Edition - Vocalized Aramaic",
            ),
        )
        .dated("A", "450 CE")
        .also_called("ב\"מ"),
        // --- Mishnah ----------------------------------------------------
        // Menukad, and the Rambam on it below is bare. spec.md §2.1's own
        // example of inconsistent coverage, and the reason `known_good_lookup`
        // compares the two ends of one link through the normalizer.
        sefer(
            "mishnah-berakhot",
            "משנה ברכות",
            "Mishnah Berakhot",
            &["Mishnah", "Seder Zeraim"],
            text(
                jagged(2, &["Perek", "Mishnah"], &["פרק", "משנה"], vec![2, 3]),
                json!([
                    [
                        "מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּעַרְבִין",
                        "מִשָּׁעָה שֶׁהַכֹּהֲנִים נִכְנָסִים לֶאֱכֹל בִּתְרוּמָתָן",
                    ],
                    ["מֵאֵימָתַי קוֹרִין אֶת שְׁמַע בְּשַׁחֲרִית"],
                ]),
                &["פרק", "משנה"],
                "Torat Emet 357",
            ),
        )
        .dated("T", "200 CE"),
        sefer(
            "rambam-on-mishnah-berakhot",
            "רמב\"ם על משנה ברכות",
            "Rambam on Mishnah Berakhot",
            &["Mishnah", "Rishonim on Mishnah", "Rambam"],
            text(
                jagged(
                    3,
                    &["Perek", "Mishnah", "Integer"],
                    &["פרק", "משנה", ""],
                    vec![1, 2, 3],
                ),
                json!([[
                    [
                        "מאימתי קורין את שמע בערבין וכו': כבר בארנו בהקדמת חבורנו זה",
                        "שזמן קריאת שמע של ערבית משעת צאת הכוכבים",
                    ],
                    ["משעה שהכהנים נכנסים לאכול בתרומתן: הוא צאת הכוכבים"],
                ]]),
                &["פרק", "משנה", ""],
                "Vilna Edition",
            ),
        )
        .dated("RI", "1168 CE")
        .by("רמב\"ם")
        .on("mishnah-berakhot"),
        sefer(
            "bartenura-on-mishnah-berakhot",
            "ברטנורא על משנה ברכות",
            "Bartenura on Mishnah Berakhot",
            &["Mishnah", "Acharonim on Mishnah", "Bartenura"],
            text(
                jagged(
                    3,
                    &["Perek", "Mishnah", "Integer"],
                    &["פרק", "משנה", ""],
                    vec![1, 1, 1],
                ),
                json!([[["מאימתי קורין את שמע בערבית - משעה שהכהנים נכנסים"]]]),
                &["פרק", "משנה", ""],
                "Vilna Edition",
            ),
        )
        .dated("RI", "1500 CE")
        .on("mishnah-berakhot"),
        // --- Halacha ----------------------------------------------------
        // Fifty-eight simanim, of which two have text. Siman 58 has to exist for
        // `שו"ע או"ח נח:א` to resolve, and inventing fifty-six simanim of
        // halacha to get there would be a fixture asserting its own invention.
        sefer(
            "shulchan-arukh/orach-chayim",
            "שולחן ערוך, אורח חיים",
            "Shulchan Arukh, Orach Chayim",
            &["Halakhah", "Shulchan Arukh"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![58, 6]),
                {
                    // Bare, because the Shulchan Arukh on Sefaria is bare — see
                    // the `SEIF` constant in `girsa-app/examples/fixture-packet.rs`,
                    // which is one of these se'ifim copied verbatim out of the
                    // corpus. Berakhot and the chumash above are menukad for the
                    // same reason: that is how the download has them.
                    let mut simanim = blanks(58);
                    simanim[0] = json!([
                        "יתגבר כארי לעמוד בבוקר לעבודת בוראו",
                        "ולא יתבייש מפני בני אדם המלעיגים עליו",
                        "ראוי לכל ירא שמים שיהא מיצר ודואג על חורבן בית המקדש",
                        "טוב מעט תחנונים בכוונה מהרבות בלא כוונה",
                    ]);
                    simanim[57] = json!([
                        "זמן קריאת שמע של שחרית מצותה שיתחיל לקרות",
                        "ואם קראה משעלה עמוד השחר יצא",
                    ]);
                    Value::Array(simanim)
                },
                &["סימן", "סעיף"],
                "Maginei Eretz: Shulchan Aruch Orach Chaim, Lemberg, 1893",
            ),
        )
        .dated("AH", "1563 CE")
        .by("יוסף קארו")
        // No `commentary_on` on the Tur, even though the Shulchan Arukh was
        // written on it: Sefaria catalogues it as a work of halacha in its own
        // right, not as a commentary, and a fixture that declared otherwise
        // would shelve it under `הלכה/שולחן ערוך/מפרשים` and quietly stop
        // matching the download. The Tur is still one hop behind it in
        // `how_it_became_halacha` — through the **edge**, which is what a chain
        // is made of. A declaration is not the only way two seforim are related,
        // and this is the pair that proves it.
        .also_called("שו\"ע או\"ח")
        .also_called("שולחן ערוך אורח חיים"),
        sefer(
            "tur/orach-chayim",
            "טור, אורח חיים",
            "Tur, Orach Chayim",
            &["Halakhah", "Tur"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![58, 2]),
                {
                    let mut simanim = blanks(58);
                    simanim[0] = json!(["יתגבר כארי לעמוד בבקר לעבודת בוראו שיהא הוא מעורר השחר"]);
                    simanim[57] = json!(["זמן קריאת שמע של שחרית מצותה עם הנץ החמה"]);
                    Value::Array(simanim)
                },
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("RI", "1340 CE")
        .by("יעקב בן אשר")
        .also_called("טור או\"ח"),
        sefer(
            "mishnah-berurah",
            "משנה ברורה",
            "Mishnah Berurah",
            &["Halakhah", "Acharonim", "Mishnah Berurah"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![58, 3]),
                {
                    let mut simanim = blanks(58);
                    simanim[0] = json!(["יתגבר כארי - כלומר שיתגבר על יצרו"]);
                    simanim[57] = json!([
                        "זמן קריאת שמע - ומצוה מן המובחר לקרותה כותיקין",
                        "משעלה עמוד השחר - היינו בדיעבד",
                    ]);
                    Value::Array(simanim)
                },
                &["סימן", "סעיף"],
                "Machon Yerushalayim",
            ),
        )
        // A range rather than a year, the way Sefaria dates a work written over
        // three decades. `how_it_became_halacha` leans on it: the Mishnah Berurah
        // and the Shulchan Arukh are both era `AH`, so on era codes alone that
        // chain is two contemporaries and does not exist. The years are what
        // make the direction knowable.
        .dated("AH", "1875 - 1905")
        .by("ישראל מאיר הכהן")
        .on("shulchan-arukh/orach-chayim")
        .also_called("מ\"ב"),
        sefer(
            "magen-avraham",
            "מגן אברהם",
            "Magen Avraham",
            &["Halakhah", "Acharonim", "Magen Avraham"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["יתגבר כארי - עיין בזוהר"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1692 CE")
        .on("shulchan-arukh/orach-chayim"),
        sefer(
            "turei-zahav-on-shulchan-arukh/orach-chayim",
            "טורי זהב על שולחן ערוך, אורח חיים",
            "Turei Zahav on Shulchan Arukh, Orach Chayim",
            &["Halakhah", "Acharonim", "Turei Zahav"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["יתגבר כארי - פירוש בזריזות"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1646 CE")
        .on("shulchan-arukh/orach-chayim"),
        sefer(
            "shulchan-arukh/yoreh-deah",
            "שולחן ערוך, יורה דעה",
            "Shulchan Arukh, Yoreh De'ah",
            &["Halakhah", "Shulchan Arukh"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 2]),
                json!([["הכל שוחטין לכתחלה ושחיטתן כשרה", "חוץ מחרש שוטה וקטן",]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1563 CE")
        .by("יוסף קארו")
        .also_called("שו\"ע יו\"ד"),
        sefer(
            "siftei-kohen-on-shulchan-arukh/yoreh-deah",
            "שפתי כהן על שולחן ערוך, יורה דעה",
            "Siftei Kohen on Shulchan Arukh, Yoreh De'ah",
            &["Halakhah", "Acharonim", "Siftei Kohen"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["הכל שוחטין - אפילו נשים"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1646 CE")
        .on("shulchan-arukh/yoreh-deah")
        .also_called("ש\"ך"),
        sefer(
            "turei-zahav-on-shulchan-arukh/yoreh-deah",
            "טורי זהב על שולחן ערוך, יורה דעה",
            "Turei Zahav on Shulchan Arukh, Yoreh De'ah",
            &["Halakhah", "Acharonim", "Turei Zahav"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["הכל שוחטין - ואפילו כותי"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1646 CE")
        .on("shulchan-arukh/yoreh-deah"),
        // On the shelf so that `a_commentary_is_not_attached_to_a_sefer_it_was_never_written_on`
        // has the two volumes the Mishnah Berurah and the Magen Avraham are *not*
        // on. A test that the Shach is absent from Orach Chayim proves nothing if
        // Even HaEzer is not on the shelf to be absent from.
        sefer(
            "shulchan-arukh/choshen-mishpat",
            "שולחן ערוך, חושן משפט",
            "Shulchan Arukh, Choshen Mishpat",
            &["Halakhah", "Shulchan Arukh"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["אין דנין דיני קנסות בבבל"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1563 CE")
        .by("יוסף קארו"),
        sefer(
            "shulchan-arukh/even-haezer",
            "שולחן ערוך, אבן העזר",
            "Shulchan Arukh, Even HaEzer",
            &["Halakhah", "Shulchan Arukh"],
            text(
                jagged(2, &["Siman", "Seif"], &["סימן", "סעיף"], vec![1, 1]),
                json!([["חייב כל אדם לישא אשה כדי לפרות ולרבות"]]),
                &["סימן", "סעיף"],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1563 CE")
        .by("יוסף קארו"),
        // --- Tanach and its mefarshim -----------------------------------
        sefer(
            "genesis",
            "בראשית",
            "Genesis",
            &["Tanakh", "Torah"],
            text(
                jagged(2, &["Perek", "Pasuk"], &["פרק", "פסוק"], vec![1, 3]),
                json!([[
                    "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ",
                    "וְהָאָרֶץ הָיְתָה תֹהוּ וָבֹהוּ וְחֹשֶׁךְ עַל פְּנֵי תְהוֹם",
                    "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי אוֹר",
                ]]),
                &["פרק", "פסוק"],
                "Miqra according to the Masorah",
            ),
        )
        .dated("T", "-1000")
        .also_called("בראשית"),
        commentary_on_genesis(
            "rashi-on-genesis",
            "רש\"י על בראשית",
            "Rashi on Genesis",
            "RI",
            "1090 CE",
            "בראשית ברא - אין המקרא הזה אומר אלא דרשני",
        ),
        commentary_on_genesis(
            "ramban-on-genesis",
            "רמב\"ן על בראשית",
            "Ramban on Genesis",
            "RI",
            "1270 CE",
            "בראשית ברא אלהים - הפסוק הזה סוד גדול",
        ),
        commentary_on_genesis(
            "ibn-ezra-on-genesis",
            "אבן עזרא על בראשית",
            "Ibn Ezra on Genesis",
            "RI",
            "1150 CE",
            "בראשית - יש אומרים כי בי\"ת בראשית משרת",
        ),
        commentary_on_genesis(
            "sforno-on-genesis",
            "ספורנו על בראשית",
            "Sforno on Genesis",
            "AH",
            "1550 CE",
            "בראשית ברא - בתחלת הזמן",
        ),
        commentary_on_genesis(
            "radak-on-genesis",
            "רד\"ק על בראשית",
            "Radak on Genesis",
            "RI",
            "1200 CE",
            "בראשית - הבי\"ת בשו\"א לפי שהוא סמוך",
        ),
        commentary_on_genesis(
            "rashbam-on-genesis",
            "רשב\"ם על בראשית",
            "Rashbam on Genesis",
            "RI",
            "1150 CE",
            "בראשית ברא - לפי פשוטו",
        ),
        commentary_on_genesis(
            "onkelos-genesis",
            "תרגום אונקלוס בראשית",
            "Onkelos Genesis",
            "T",
            "150 CE",
            "בְּקַדְמִין בְּרָא יְיָ יָת שְׁמַיָּא וְיָת אַרְעָא",
        ),
        // A branch schema: a named node that becomes a level of the address and a
        // default node that does not. 1,101 of Sefaria's 6,595 schemas are this
        // shape and nothing else on the fixture shelf exercises the walker's
        // other half.
        sefer(
            "abarbanel-on-ezekiel",
            "אברבנאל על יחזקאל",
            "Abarbanel on Ezekiel",
            &["Tanakh", "Rishonim on Tanakh", "Abarbanel"],
            text(
                json!({
                    "nodes": [
                        {
                            "title": "Introduction",
                            "heTitle": "הקדמה",
                            "nodeType": "JaggedArrayNode",
                            "depth": 1,
                            "addressTypes": ["Integer"],
                        },
                        // **A section whose name is also a level word.** `שער`
                        // is one of the 29 words the resolver reads as a label
                        // — `שער א'` is gate one — so a citation into this
                        // section resolves to perek א' of the default node
                        // instead, which is a real place and the wrong one.
                        // Nothing else on this shelf is shaped that way, and it
                        // is not a rare shape: 122 chalakim of the 7,627 on a
                        // real shelf are still it.
                        {
                            "title": "Gate",
                            "heTitle": "שער",
                            "nodeType": "JaggedArrayNode",
                            "depth": 1,
                            "addressTypes": ["Integer"],
                        },
                        {
                            "title": "",
                            "default": true,
                            "nodeType": "JaggedArrayNode",
                            "depth": 2,
                            "addressTypes": ["Perek", "Pasuk"],
                        },
                    ]
                }),
                json!({
                    "Introduction": ["אמר יצחק בן יהודה אברבנאל", "הנה ראיתי לבאר"],
                    "Gate": ["שער ראשון - בטעם הנבואה"],
                    "": [["ויהי בשלשים שנה - הנבואה הראשונה"]],
                }),
                &[],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1500 CE"),
        // --- The seam between the two downloads -------------------------
        // Sefaria files an acharon on the Gemara under `Talmud/Bavli/Acharonim on
        // Talmud`, in English. Otzaria files one under `תלמוד בבלי/אחרונים`, in
        // Hebrew. Both are right about their own download and neither is a shelf.
        // Both of these have to land in one place or
        // `the_two_corpora_land_on_the_same_shelf` is asserting about one corpus.
        sefer(
            "pnei-yehoshua-on-berakhot",
            "פני יהושע על ברכות",
            "Penei Yehoshua on Berakhot",
            &["Talmud", "Bavli", "Acharonim on Talmud", "Penei Yehoshua"],
            text(
                jagged(
                    3,
                    &["Talmud", "Integer", "Integer"],
                    &["דף", "שורה", ""],
                    vec![1, 1, 1],
                ),
                amudim(6, &[(daf(2, 'a'), json!([["מאימתי קורין - קשה לי"]]))]),
                &["דף", "שורה", ""],
                "Vilna Edition",
            ),
        )
        .dated("AH", "1730 CE")
        .on("bavli/berakhot"),
        Sefer {
            base: Vec::new(),
            variants: Vec::new(),
            ..sefer(
                "otzaria/tzlach-berakhot",
                "צל\"ח על ברכות",
                "Tzlach on Berakhot",
                &["תלמוד בבלי", "אחרונים", "צל\"ח"],
                Body::Otzaria {
                    txt: "<h1>צל\"ח על ברכות</h1>\n\
                          <h2>דף ב עמוד א</h2>\n\
                          מאימתי קורין את שמע בערבית. הנה יש לדקדק בלשון המשנה\n\
                          ועיין בפני יהושע שהאריך בזה\n\
                          <h2>דף ב עמוד ב</h2>\n\
                          מאי שנא דתני בערבית ברישא. ולפי מה שכתבנו\n"
                        .to_string(),
                },
            )
        }
        .dated("AH", "1780 CE"),
    ]
}

/// One of the seven mefarshim printed around a chumash, all the same shape.
fn commentary_on_genesis(
    slug: &str,
    he: &str,
    en: &str,
    era: &str,
    comp_date: &str,
    first: &str,
) -> Sefer {
    sefer(
        slug,
        he,
        en,
        &["Tanakh", "Rishonim on Tanakh"],
        text(
            jagged(
                3,
                &["Perek", "Pasuk", "Integer"],
                &["פרק", "פסוק", ""],
                vec![1, 1, 1],
            ),
            json!([[[first]]]),
            &["פרק", "פסוק", ""],
            "Vilna Edition",
        ),
    )
    .dated(era, comp_date)
    .on("genesis")
}

/// The one work whose source file this crate rewrites, for the re-import tests.
///
/// Orach Chayim with **a se'if inserted at the front of siman 1** — which is the
/// case spec.md §3 is written about and the case that renumbered 4,170 segments
/// the last time it happened. Handed to [`reimport`], it exercises
/// `continuity::align` and the redirect table on a shelf a test can build.
#[must_use]
pub fn orach_chayim_with_a_seif_inserted() -> Sefer {
    let mut sefer = shelf()
        .into_iter()
        .find(|s| s.slug == "shulchan-arukh/orach-chayim")
        .expect("orach chayim is on the fixture shelf");
    if let Body::Sefaria { text, schema, .. } = &mut sefer.body {
        if let Some(simanim) = text.as_array_mut() {
            if let Some(first) = simanim.first_mut().and_then(Value::as_array_mut) {
                first.insert(
                    0,
                    json!("הַמַּשְׁכִּים לְהִתְחַנֵּן לִפְנֵי בּוֹרְאוֹ יְכַוֵּן לְשָׁעוֹת שֶׁמִּשְׁתַּנּוֹת בָּהֶן הַמִּשְׁמָרוֹת"),
                );
            }
        }
        // The schema says one more se'if, because upstream would say so too.
        schema["lengths"] = json!([58, 7]);
    }
    sefer
}
